namespace MVVM.Generator.Runtime;

/// <summary>
/// The property-path observer emitted once per consuming assembly. Chained
/// dependencies need runtime subscription management that a setter-side
/// OnPropertyChanged call cannot express, so the generator renders calls into
/// this helper rather than open-coding the plumbing per property.
/// </summary>
internal static class ChainObserverSource
{
    public const string HintName = "ChainObserver.g.cs";

    public const string Source = """
        // <auto-generated/>
        #nullable enable

        using System;
        using System.Collections.Specialized;
        using System.ComponentModel;

        namespace MVVM.Generator.Runtime
        {
            /// <summary>
            /// Observes one property path rooted at a head value, invoking a callback
            /// whenever any link along the path changes.
            /// </summary>
            /// <remarks>
            /// Each level re-resolves and re-subscribes the levels below it when its own
            /// link changes, so swapping out an intermediate object moves the whole
            /// subscription subtree with it. The head itself is not observed here: the
            /// generated setter for the head property calls Attach again, and that is
            /// what keeps a reassigned head live.
            /// </remarks>
            internal sealed class ChainObserver
            {
                /// <summary>One property access along the observed path.</summary>
                internal sealed class Link
                {
                    public Link(string propertyName, Func<object, object?> resolve, bool observeCollection)
                    {
                        PropertyName = propertyName;
                        Resolve = resolve;
                        ObserveCollection = observeCollection;
                    }

                    /// <summary>Name of the property this link reads on its owner.</summary>
                    public string PropertyName { get; }

                    /// <summary>Reads this link's value from its owner.</summary>
                    public Func<object, object?> Resolve { get; }

                    /// <summary>
                    /// True when the observed expression reads the contents of this link
                    /// rather than only the reference, so the value also needs a
                    /// CollectionChanged subscription.
                    /// </summary>
                    public bool ObserveCollection { get; }
                }

                private readonly Link[] _links;
                private readonly Action _onChanged;
                private readonly object?[] _owners;
                private readonly PropertyChangedEventHandler _propertyChangedHandler;
                private readonly NotifyCollectionChangedEventHandler _collectionChangedHandler;
                private INotifyCollectionChanged? _collection;

                public ChainObserver(Action onChanged, params Link[] links)
                {
                    _onChanged = onChanged ?? throw new ArgumentNullException(nameof(onChanged));
                    _links = links ?? throw new ArgumentNullException(nameof(links));
                    _owners = new object?[_links.Length];
                    _propertyChangedHandler = OnOwnerPropertyChanged;
                    _collectionChangedHandler = OnCollectionChanged;
                }

                /// <summary>
                /// Points the observer at a new head value, releasing every subscription
                /// taken against the previous one.
                /// </summary>
                public void Attach(object? head)
                {
                    Detach();
                    if (head == null || _links.Length == 0) return;

                    _owners[0] = head;
                    SubscribeFrom(0);
                }

                /// <summary>Releases every subscription this observer holds.</summary>
                public void Detach() => DetachFrom(0);

                private void SubscribeFrom(int level)
                {
                    for (var i = level; i < _links.Length; i++)
                    {
                        var owner = _owners[i];
                        if (owner == null) return;

                        if (owner is INotifyPropertyChanged notifier)
                            notifier.PropertyChanged += _propertyChangedHandler;

                        var value = ResolveSafely(i);

                        if (i == _links.Length - 1)
                        {
                            if (_links[i].ObserveCollection && value is INotifyCollectionChanged collection)
                            {
                                _collection = collection;
                                collection.CollectionChanged += _collectionChangedHandler;
                            }
                            return;
                        }

                        _owners[i + 1] = value;
                    }
                }

                private void DetachFrom(int level)
                {
                    if (_collection != null)
                    {
                        _collection.CollectionChanged -= _collectionChangedHandler;
                        _collection = null;
                    }

                    for (var i = _links.Length - 1; i >= level; i--)
                    {
                        if (_owners[i] is INotifyPropertyChanged notifier)
                            notifier.PropertyChanged -= _propertyChangedHandler;

                        _owners[i] = null;
                    }
                }

                private void OnOwnerPropertyChanged(object? sender, PropertyChangedEventArgs e)
                {
                    if (sender == null) return;

                    var level = LevelOf(sender);
                    if (level < 0) return;

                    // A null or empty name is the INotifyPropertyChanged convention for
                    // "every property changed", so it invalidates this link as well.
                    var name = e?.PropertyName;
                    if (!string.IsNullOrEmpty(name) && name != _links[level].PropertyName) return;

                    // Levels at and below `level` stay subscribed, so rebuilding starts
                    // beneath them and nothing is subscribed twice.
                    DetachFrom(level + 1);

                    if (level + 1 < _links.Length)
                    {
                        _owners[level + 1] = ResolveSafely(level);
                        SubscribeFrom(level + 1);
                    }
                    else if (_links[level].ObserveCollection
                        && ResolveSafely(level) is INotifyCollectionChanged collection)
                    {
                        _collection = collection;
                        collection.CollectionChanged += _collectionChangedHandler;
                    }

                    _onChanged();
                }

                private object? ResolveSafely(int level)
                {
                    var owner = _owners[level];
                    if (owner == null) return null;

                    try
                    {
                        return _links[level].Resolve(owner);
                    }
                    catch (NullReferenceException)
                    {
                        // A getter along the path can dereference state that is not
                        // populated yet. The subscription on this level still fires once
                        // it is, which re-resolves from here.
                        return null;
                    }
                }

                private void OnCollectionChanged(object? sender, NotifyCollectionChangedEventArgs e) => _onChanged();

                private int LevelOf(object sender)
                {
                    for (var i = 0; i < _owners.Length; i++)
                    {
                        if (ReferenceEquals(_owners[i], sender)) return i;
                    }
                    return -1;
                }
            }
        }
        """;
}
